-- Migration 004: Ensure circuit_breakers has all fields for existing databases
ALTER TABLE circuit_breakers
ADD COLUMN IF NOT EXISTS success_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS threshold_failures INTEGER NOT NULL DEFAULT 5,
ADD COLUMN IF NOT EXISTS cool_down_seconds INTEGER NOT NULL DEFAULT 30,
ADD COLUMN IF NOT EXISTS opened_at TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
